### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by AndrewIsOffline** [Dischan/dismae#1]
I keep getting an error when starting the UI: http://sta.sh/013gqb882caf
In addition, the auto-update keeps saying that there's a new version available, even though the version that it says it is updating to is the same as the one that I'm using. It will even say this after the download is complete and I restart the application.

**Comment by JeremyMiller** [comment]
Hello Andrew,

Thanks for the report. Could you tell me what version of Windows you are using? Also, did you get this error the first time you started the UI?

**Comment by AndrewIsOffline** [comment]
I'm using Windows 10 64 bit and yes I got the error on the first run.

**Comment by JeremyMiller** [comment]
Hello Andrew,

I published a new version that should fix the issue. Please open dismae again and allow it to update.

If it doesn't actually update (I'm not sure if it will due to the bug), you can download the new version here: https://github.com/Dischan/dismae-ui/releases/download/v0.0.5/DismaeSetup-0.0.5-ia32.exe

Please let me know whether the automatic update works and whether the new version works.

**Comment by AndrewIsOffline** [comment]
Running the 0.0.4 installer did download the update, but won't recognize that it's installed and keeps going back to 0.0.4 and re-updating. The 0.0.5 installer isn't bringing up any Javascript errors, but it keeps saying that the program is outdated, even though the update is installed.

**Comment by JeremyMiller** [comment]
Hello Andrew.

Thanks for trying it out. I updated the 0.0.5 build again. Could you redownload it and try it again? 

https://github.com/Dischan/dismae-ui/releases/download/v0.0.5/DismaeSetup-0.0.5-ia32.exe

**Comment by AndrewIsOffline** [comment]
The new update says it's up-to-date. I also renamed the "dismae" appdata folder to test it and it updated correctly.
